
const sf = [
    "LOBSTER",
    "SALMON",
    "TUNA",
    "CRAB",
    "SCALLOP",
    "CLAM",
    "SHRIMP",
    "SQUID",
    "OYSTERS",
    "COD",
    "HALIBUT",
    "TROUT",
    "SEA BASS",
    "MUSSELS",
    "CATFISH",
    "SNAPPER",
    "MAHI MAHI",
    "PIKE",
    "WHITEFISH",
    "GROUPER",
    "FLOUNDER",
    "SWORDFISH",
    "CRAWFISH",
    "LINGCOD",
    "MONKFISH",
    "HADDOCK",
    "SHARK",
    "EEL",
    "WALLEYE",
    "PERCH",
    "SAILFISH",
    "TILAPIA",
    "CARP",
    "PRAWNS",
    "ANCHOVY",
    "HERRING",
    "ROE",
    "BASS",
    "OCTOPUS",
    "CAVIAR",
    "FISH TACOS",
    "LOBSTER ROLL",
    "BAKED COD",
    "FRIED FISH",
    "FISH STEW",
    "CRAB CAKES",
    "SHRIMP COCKTAIL",
    "SEAFOOD CHOWDER",
    "CALAMARI",
    "FISH CURRY",
    "STEAMED CLAMS",
    "BBQ SHRIMP",
    "CRAB BISQUE",
    "SEA URCHIN",
    "TUNA STEAK",
    "GRILLED FISH",
    "SMOKED SALMON",
    "GARLIC PRAWNS",
    "CHILI CRAB",
    "SQUID INK",
    "MISO SALMON",
    "BUTTER SHRIMP",
    "KING CRAB",
    "SEAFOOD PASTA",
    "POACHED FISH",
    "STUFFED CLAMS",
    "TEMPURA SHRIMP",
    "GRILLED SQUID",
    "CLAM CHOWDER",
    "FRIED CALAMARI",
    "TUNA SASHIMI",
    "CRAB FRITTERS",
    "PEPPERED FISH",
    "CITRUS SALMON",
    "CRAB SOUP",
    "FISH BURGER",
    "BLACKENED FISH",
    "LEMON TUNA",
    "ROASTED SALMON",
    "CRAB SALAD",
    "SEAFOOD RISOTTO",
    "FISH FILLETS",
    "FRIED CLAMS",
    "GRILLED TROUT",
    "SPICY TUNA",
    "SHRIMP SCAMPI",
    "CHILLED SHRIMP",
    "FISH SOUP",
    "GARLIC FISH",
    "STIR FRY SQUID",
    "TUNA POKE",
    "SAKE SALMON",
    "SEAFOOD ROLL",
    "SHRIMP TEMPURA",
    "CRAB STICKS",
    "SCALLOP RISOTTO"
];

const it = [
    "LASAGNA",
    "GNOCCHI",
    "RISOTTO",
    "RAVIOLI",
    "CARBONARA",
    "MINESTRONE",
    "TORTELLINI",
    "FETTUCCINE",
    "PIZZA",
    "BRUSCHETTA",
    "PANZANELLA",
    "POLENTA",
    "OSSOBUCO",
    "TIRAMISU",
    "CANNOLI",
    "PANNACOTTA",
    "SPAGHETTI",
    "CALZONE",
    "CAPRESE",
    "BAGNA CAUDA",
    "ARANCINI",
    "FIORENTINA",
    "PENNE",
    "PESTO",
    "BIGOLI",
    "MOSTARDA",
    "TAGLIATELLE",
    "ZUPPA TOSCANA",
    "PROSCIUTTO",
    "FRITTATA",
    "CIABATTA",
    "CROSTATA",
    "PARMIGIANA",
    "MELANZANE",
    "BISCOTTI",
    "STRACCIATELLA",
    "CASONCELLI",
    "SORBETTO",
    "COTTOLETTA",
    "RIBOLLITA",
    "ZUCCOTTO",
    "FARINATA",
    "PICCATA",
    "PIZZELLE",
    "FRITTELLE",
    "AFFOGATO",
    "CANESTRELLI",
    "PANDORO",
    "AMARETTI",
    "GRISSINI",
    "BOTTARGA",
    "ZAMPONE",
    "FREGOLA",
    "PANETTONE",
    "CRESPELLE",
    "BACCALA",
    "CASSATA",
    "TARTUFO",
    "AGNELLO",
    "INZIMINO",
    "STRUFFOLI",
    "CANNELLONI",
    "CIAMBELLE",
    "MACCHERONI",
    "RUSTICO",
    "CACIOCAVALLO",
    "TORTA PASQUALINA",
    "PANFORTE",
    "CASTAGNOLE",
    "BOMBA CALABRESE",
    "SALSICCIA",
    "SCALOPPINE",
    "POLPETTE",
    "PICCATA",
    "BRASATO",
    "CASSOULET",
    "COTTOLETTA",
    "RISOTTO",
    "SPAGHETTINI",
    "SPUMONI",
    "LIMONCELLO",
    "GELATO",
    "TORTINO",
    "TARALLI",
    "SORBETTO",
    "AMATRICIANA",
    "POMODORO",
    "PASTICCIO",
    "SCROCCHIANTE",
    "PORCHETTA",
    "SFOGLIATELLE",
    "ZABAGLIONE",
    "SUGO",
    "FUSILLI",
    "PECORINO",
    "TROFIE",
    "CAMPANELLE",
    "FRASCATI",
    "MONTANARA"
];

const af = [
    "BURGERS",
    "HOT DOGS",
    "MEATLOAF",
    "FRIED CHICKEN",
    "CORN BREAD",
    "BBQ RIBS",
    "APPLE PIE",
    "CHILI",
    "PANCAKES",
    "WAFFLES",
    "COLESLAW",
    "GRITS",
    "POT ROAST",
    "MAC N CHEESE",
    "CLAM BAKE",
    "PULLED PORK",
    "TATER TOTS",
    "PORK CHOPS",
    "CHICKEN WINGS",
    "BEEF STEW",
    "TUNA MELT",
    "SLOPPY JOE",
    "BANANA BREAD",
    "BISCUITS",
    "CORN DOG",
    "PUMPKIN PIE",
    "CHICKEN POT",
    "CHEESEBURGER",
    "BROWNIES",
    "FRIED CATFISH",
    "LOBSTER MAC",
    "STUFFED PEPPERS",
    "TEXAS TOAST",
    "BLT SANDWICH",
    "RANCH SALAD",
    "COBB SALAD",
    "CHEDDAR BISCUIT",
    "PHILLY CHEESE",
    "HASH BROWNS",
    "KEY LIME PIE",
    "FRIED OKRA",
    "GRILLED CHEESE",
    "BACON WRAP",
    "CORN FRITTER",
    "BUFFALO WINGS",
    "ONION RINGS",
    "BAKED BEANS",
    "STEAK FRITES",
    "MASHED POTATO",
    "BBQ CHICKEN",
    "FRIED PICKLES",
    "SUGAR COOKIES",
    "CHOCOLATE PIE",
    "CRAB FRITTER",
    "SPARE RIBS",
    "CHILI DOG",
    "BEEF BRISKET",
    "CINNAMON ROLL",
    "MAPLE DONUT",
    "GRAVY FRIES",
    "PORK RINDS",
    "TEXAS BURGER",
    "HUSH PUPPIES",
    "CARAMEL CORN",
    "PEACH COBBLER",
    "CHERRY PIE",
    "BAKED SALMON",
    "FRIED SHRIMP",
    "PORK BELLY",
    "VEGGIE BURGER",
    "TURKEY SAND",
    "CRAB CAKES",
    "SWEET TEA",
    "CHEDDAR FRIES",
    "BACON MAC",
    "POTATO SALAD",
    "FRIED OYSTER",
    "BISON BURGER",
    "STUFFED BELL",
    "PUMPKIN ROLL",
    "CHOWDER BOWL",
    "SOUTHERN GRIT",
    "PEANUT BRITTLE",
    "CHEESE FRIES",
    "SMOKED SAUSAGE",
    "BBQ PULLED",
    "ROAST TURKEY",
    "SHEPHERD PIE",
    "HONEY HAM",
    "STRAWBERRY PIE",
    "ICE CREAM CAKE",
    "CARROT CAKE"
];


const da = [
    "CUPCAKES",
    "CHEESECAKE",
    "TRIFLE",
    "GELATIN",
    "SORBET",
    "DONUTS",
    "MOUSSE",
    "FUDGE",
    "PIE CRUST",
    "BLONDIES",
    "CANDY",
    "TARTUFO",
    "JELLY",
    "CAKE POP",
    "FRUIT TART",
    "CHURROS",
    "TOFFEE",
    "MERINGUE",
    "TARTS",
    "CAKE SLICE"
];


const ra = [
    "POTATOES",
    "TOMATOES",
    "ONIONS",
    "CARROTS",
    "CELERY",
    "GARLIC",
    "GINGER",
    "PARSLEY",
    "LEMONS",
    "ORANGES",
    "PEACHES",
    "PLUMS",
    "APPLES",
    "BANANAS",
    "CHERRIES",
    "MELONS",
    "CUCUMBER",
    "ZUCCHINI",
    "SPINACH",
    "CABBAGE",
    "LETTUCE",
    "PEPPERS",
    "RADISHES",
    "TURNIPS",
    "SQUASH",
    "EGGPLANT",
    "BROCCOLI",
    "CAULIFLOWER",
    "CHILI",
    "THYME",
    "BASIL",
    "OREGANO",
    "SAGE",
    "DILL",
    "FLOUR",
    "SALT",
    "SUGAR",
    "BUTTER",
    "HONEY",
    "VINEGAR",
    "OLIVE OIL",
    "CANOLA OIL",
    "COCOA",
    "YEAST",
    "ALMONDS",
    "PECANS",
    "PEANUTS",
    "WALNUTS",
    "RAISINS",
    "DATES",
    "CINNAMON",
    "CUMIN",
    "TURMERIC",
    "PAPRIKA",
    "CLOVES",
    "VANILLA",
    "SESAME",
    "MUSTARD",
    "PEPPER",
    "CHERRIES",
    "CRANBERRY",
    "STRAWBERRY",
    "BLUEBERRY",
    "BLACKBERRY",
    "KIWIFRUIT",
    "MANGOES",
    "LIMES",
    "FIGS",
    "PRUNES",
    "GRAPES",
    "RHUBARB"
];

const sa = [
    "TACOS",
    "ENCHILADA",
    "QUESADILLA",
    "TAMALES",
    "GUACAMOLE",
    "CHURROS",
    "EMPANADA",
    "AREPAS",
    "CEVICHE",
    "PUPUSAS",
    "CHIMICHURRI",
    "SALSAS",
    "MOLE",
    "CHILAQUILES",
    "GORDITAS",
    "ELOTE",
    "TOSTADAS",
    "CARNE ASADA",
    "FIDEO",
    "SOPAPILLAS",
    "COCHINITA",
    "CHORIPAN",
    "TORTILLA",
    "FLAN",
    "CACHAPAS",
    "SALTEÑAS",
    "AJIACO",
    "FEIJOADA",
    "PÃO DE QUEIJO",
    "CUCURUCHO",
    "HUARACHES",
    "ARROZ CON POLLO",
    "PAN DULCE",
    "BIRRIA",
    "CAMOTES",
    "FRIJOLITOS",
    "ALFAJORES",
    "MILANESA",
    "SOPA SECA",
    "CHICHARRON",
    "YUCCA FRIES",
    "CALABACITA",
    "PICADILLO",
    "POLLO ASADO",
    "PICO DE GALLO",
    "HUEVOS RANCHEROS",
    "CHARRO BEANS",
    "FLAUTAS",
    "NACHOS",
    "MARGARITA",
    "MOJO VERDE",
    "CAIPIRINHA"
];


function filterStringsByLength() {
    let arrOfArrs = [it,af,sf,sa,ra,da];
    return arrOfArrs.flat().filter(item => item.length < 10);
}

module.exports = filterStringsByLength;
